version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  eslint:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run: npm run lint
  typedoc:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run: npm run docs:update -- --emit none

workflows:
  test:
    jobs:
      - eslint
      - typedoc
      - node/test:
          override-ci-command: npm ci && npx lerna run build --scope=@prelude-io/core
          matrix:
            parameters:
              version:
                - "18.13"
                - "16.19"
          pkg-manager: npm
